export const almacenInicial = {
  id: 'almacen',
  nombre: 'Centro de distribucion',
  direccion: 'Av. Salvador Diaz Miron 2100',
  lat: 19.1738,
  lon: -96.1342,
  peso: 0,
};

export const entregasIniciales = [
  {
    id: 'e1',
    nombre: 'Abarrotes La Esquina',
    direccion: 'Independencia 450, Centro',
    lat: 19.1902,
    lon: -96.143,
    peso: 18,
    prioridad: 'normal',
  },
  {
    id: 'e2',
    nombre: 'Farmacia del Puerto',
    direccion: 'Costa de Oro 118',
    lat: 19.1608,
    lon: -96.1189,
    peso: 7,
    prioridad: 'alta',
  },
  {
    id: 'e3',
    nombre: 'Restaurante El Muelle',
    direccion: 'Blvd. Ruiz Cortines 890',
    lat: 19.1361,
    lon: -96.1067,
    peso: 32,
    prioridad: 'normal',
  },
  {
    id: 'e4',
    nombre: 'Papeleria Escolar',
    direccion: 'Av. Cuauhtemoc 76',
    lat: 19.2041,
    lon: -96.1352,
    peso: 12,
    prioridad: 'baja',
  },
  {
    id: 'e5',
    nombre: 'Taller Mecanico Rivera',
    direccion: 'Prolongacion Hidalgo 1240',
    lat: 19.1523,
    lon: -96.1521,
    peso: 45,
    prioridad: 'normal',
  },
  {
    id: 'e6',
    nombre: 'Tienda Mandinga',
    direccion: 'Carretera Mandinga km 4',
    lat: 19.1245,
    lon: -96.0954,
    peso: 23,
    prioridad: 'baja',
  },
  {
    id: 'e7',
    nombre: 'Hotel Playa Norte',
    direccion: 'Blvd. Avila Camacho 320',
    lat: 19.1819,
    lon: -96.1163,
    peso: 15,
    prioridad: 'alta',
  },
  {
    id: 'e8',
    nombre: 'Mini Super Las Vegas',
    direccion: 'Calle 12 num. 55',
    lat: 19.1455,
    lon: -96.1398,
    peso: 28,
    prioridad: 'normal',
  },
];

export const ajustesIniciales = {
  velocidad: 28,
  rendimiento: 11,
  precioLitro: 24.5,
  capacidad: 100,
  usarCapacidad: false,
};
